steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        export DOCKER_BUILDKIT=1
        docker build -t asia-southeast1-docker.pkg.dev/ecoriver/ecoriver/worker .
    env:
      - "DOCKER_BUILDKIT=1"
timeout: "14400s" # 4 hours in seconds
images:
  - "asia-southeast1-docker.pkg.dev/ecoriver/ecoriver/worker"
